### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by TanKucukhas** [tegon/clone-org-repos#10]
I'm trying to clone a copy of all the repo's in a team for enterprise account. I have already set the base_uri on the config file but I'm still getting this error on the console as soon as the command executed. I have tried ssh https git token all of them with same issue; 

```shell
INFO: Requesting github repositories for xxx with url https://github.xxx.com/xxx/repos?per_page=100&type=all ...
ERROR: Error: unable to verify the first certificate
INFO: error executing request 
```

**Comment by tegon** [comment]
Hi, thank you for reporting this. 
You said you already changed the  [`BASE_URI`](https://github.com/tegon/clone-org-repos/blob/master/lib/github.js#L8) to the correct one, but what method of authentication you're using? (token or password?)

**Comment by tegon** [comment]
Closing due to lack of information. If anyone has this problem, please leave a comment and I'll reopen.
