### ISSUE TITLE
problem with passing clone settings?

### ISSUE THREAD

**Issue by chiefjester** [tegon/clone-org-repos#11]
Hi, I wanted to pass two settings for clone, which is clone a branch and `--single branch`.
It seems I'm getting a status 129 / git error.

So here's an example command that reproduces that error
```shell
cloneorg twitter -o secureheaders --gitsettings='--single-branch --branch clear-site-patch'
```

**Comment by tegon** [comment]
Hi, sorry for the late response.
Looks like currently the code only works with one git setting. I'll try to fix with as soon as I can.
Thanks for reporting this!

**Comment by tegon** [comment]
Actually, the fix was easier than I thought 😄 
Can you update to version `0.2.6` and test so see if it's working correctly now?

**Comment by chiefjester** [comment]
hi @tegon works now!  Thanks!

Side note: Any chance you can point me on how to clone repos that "ends with" a string?

eg. `.backbone` ?

**Comment by tegon** [comment]
Thanks 😄 

You can use the `regexp` option. I'm not sure what the regex will be, I'm guessing something like this:
```bash
cloneorg organization -o '\.backbone$' -r true
```
