### ISSUE TITLE
Option to clone wikis as well

### ISSUE THREAD

**Issue by cabloo** [tegon/clone-org-repos#12]
It would be really handy to be able to clone any existing Wikis as well which just requires adding a `.wiki` before `.git` (and doing some error checking to make sure the wiki exists).

**Comment by tegon** [comment]
That sounds great! Would you mind sending a PR to add this feature? 
I'm having trouble to find a time to work on this lately 😞

**Comment by cabloo** [comment]
I wrote this command which needs to be run after the regular `cloneorg` command is run. I too am quite short on time, otherwise would have come up with a real solution and submitted it.

This script shows an error for every repo that does not have a wiki, but does not create a folder for those missing. It assumes all repos are stored in the `repos` folder.

```bash
#!/usr/bin/env bash

ORG=SomeGitHubOrganizationOrUser
DIR=$(pwd)
cd $DIR/repos;
for i in $(ls); do
  git clone git@github.com:$ORG/$i.wiki.git
done
```

**Comment by tegon** [comment]
I see. Since you solved the problem with a simple solution, I think we should close this for now.
If in the future you - or myself - find a time to submit a solution we can reopen the issue.
Thanks.
