### ISSUE TITLE
128

### ISSUE THREAD

**Issue by ShalokShalom** [tegon/clone-org-repos#13]
Each repo fails to clone with error code 128

I did as you advice:  ```./cloneorg -u shalokshalom KCP-quarantine-area```

`ERROR: git clone failed with status 128 on git@github.com:KCP-quarantine-area/ktp.git`

**Comment by spacedsweden** [comment]
its ssh default, so if you have not set that up, use --a https

**Comment by ShalokShalom** [comment]
Thanks :)
