### ISSUE TITLE
Private Repos

### ISSUE THREAD

**Issue by smhanes** [tegon/clone-org-repos#6]
Does or will this in the future work for private repos in an org? If it currently does, how? I'm having issues with 128 errors.

**Comment by tegon** [comment]
It should if the user has access to the repositories. Can you paste the error here?

**Comment by smhanes** [comment]
Command I'm using:    cloneorg xxxxx -u ownerOfOrg

```
INFO: Requesting github repositories for xxxxx with url https://api.github.com/orgs/xxxxx/repos?per_page=100&type=all ...
INFO: cloning git@github.com:xxxxx/loops_-assignment.git
ERROR: git clone failed with status 128
```

**Comment by smhanes** [comment]
Problem solved. Two different issues: Had to use a personal auth token, https, and logging in with organization owner acct (assuming this was a Git prompt). Also, added a Git cache helper to my git install to cache the user/pass for 15 minutes rather than being prompted for each repo.
